<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title><?= $this->title ?></title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <?php $this->section('head') ?>
        <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
        <link href="http://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic,700italic" media="screen" rel="stylesheet" type="text/css" >
        <link rel="stylesheet" type="text/css" href="/css/app.css">
    <?php $this->stop() ?>
</head>

<body>
    <header>
        <nav class="navbar navbar-inverse navbar-fixed-top">
            <div class="container-fluid">
                <div class="navbar-header">
                    <a class="navbar-brand" href="<?= $this->pathFor('home') ?>">SSOAuth</a>
                </div>
                <ul class="nav navbar-nav navbar-right">
                    <?php if ($this->currentUser): ?>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><?= $this->currentUser->first_name ?> <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href="#" onclick="$('form#deleteSession').submit(); return false;">Logout</a></li>
                                <li><a href="#"><span class="glyphicon glyphicon-log-out"></span> Logout</a></li>
                            </ul>
                        </li>
                    <?php else: ?>
                        <li><a href="<?= $this->pathFor('register') ?>"><span class="glyphicon glyphicon-user"></span> Register</a></li>
                        <li><a href="<?= $this->pathFor('login') ?>"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
                    <?php endif; ?>
                </ul>
            </div>
        </nav>
    </header>

    <div class="container">
        <?php if (isset($this->messages['success'])): ?>
            <div class="alert alert-success">
                <?=$this->messages['success']; ?>
            </div>
        <?php endif; ?>

        <?php if (isset($this->messages['errors'])): ?>
            <div class="alert alert-danger alert-important">
                <ul>
                    <?php foreach ($this->messages['errors'] as $error): ?>
                        <li><?= $error ?></li>
                    <?php endforeach; ?>
                </ul>
            </div>
        <?php endif; ?>

        <?php $this->section('content') ?>
        <?php $this->stop() ?>
    </div>

    <?php $this->section('scripts') ?>
        <script src="https://code.jquery.com/jquery-1.12.0.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
        <script src="/js/app.js" type="text/javascript"></script>
    <?php $this->stop() ?>
</body>

</html>
