<?php $this->layout('layouts/main'); ?>

<?php $this->section('content') ?>
    <p>Hello <?= $user->first_name ?>,</p>

    <p>We received a request to reset the password associated with this email address. Click the link below to proceed to reset your password.</p>

    <p>If you did not request to reset your password you can safely ignore this email.</p>

    <p><a href="http://sso.japantravel.com/accounts/resetpassword?token=<?= $this->token ?>">http://sso.japantravel.com/accounts/resetpassword?token=<?= $this->token ?></a></p>

    <p>If clicking the link doesn't work, you can copy and paste the link into your browser's address bar.</p>

    <p>Sincerely,<br>
    <br>
    SSO Team</p>
<?php $this->replace() ?>
