Hello <?= $user->first_name ?>,

We received a request to reset the password associated with this email address. Click the link below to proceed to reset your password.

If you did not request to reset your password you can safely ignore this email.

http://sso.japantravel.com/accounts/resetpassword?token=<?= $this->token ?>

If clicking the link doesn't work, you can copy and paste the link into your browser's address bar.

Sincerely,
SSO Team
